# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_blog', '0002_auto_20160906_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='publicacao',
            field=models.DateTimeField(),
        ),
    ]
