# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_blog', '0003_auto_20160923_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='publicacao',
            field=models.DateTimeField(verbose_name='Data de publica\xe7\xe3o'),
        ),
    ]
